### ISSUE TITLE
Can't format custom message for failed-assertion  form

### ISSUE THREAD

**Issue by arichiardi** [joaotavora/fiasco#29] opened 2019-11-04 01:48 UTC
Hi there, I am executing some test in `fiasco` and it seems to fail properly.

The problem is that I get something like:

```lisp
Can't format custom message for failed-assertion form (is
                                                       (equal
                                                        (list
                                                         '(foo
                                                           bar))
                                                        (compute-graph
                                                         '(foo/bar))))
```

It is a bit hard for me to understand if I have a problem in my setup (being a super newbie) or it is a problem in the library.

Thank you for any feedback/answer and for maintaining this library!

**Comment by joaotavora** [comment] 2019-11-04 15:05
Hi @arichiardi 

I can't reproduce this, but then again, I don't know exactly what you are doing.   Can you provide a small example using fiasco that demonstrates the error?

**Comment by arichiardi** [comment] 2019-11-04 17:00
Hi Joao, thanks for the prompt answer.

This is my test file

```lisp
(fiasco:define-test-package #:resource-graph-test
  (:use :resource-graph :fiasco))

(in-package :resource-graph-test)

(rename-package 'resource-graph 'resource-graph '(rg))

(deftest naive/test ()
  (fiasco:is (eql 1 0)))

(fiasco:run-package-tests
 :verbose t
 :describe-failures t
 :interactive t)
```

and this is the backtrace:

```
Test assertion failed when running naive/test:

Can't format custom message for failed-assertion form (is
                                                       (eql 1 0))
   [Condition of type fiasco::failed-assertion]

Restarts:
 0: [continue] Roger, go on testing...
 1: [continue] Skip the rest of the test naive/test and continue by returning (values)
 2: [retest] Rerun the test naive/test
 3: [continue] Skip the rest of the test fiasco-suites::resource-graph-test and continue by returning (values)
 4: [retest] Rerun the test fiasco-suites::resource-graph-test
 5: [continue-without-debugging] Turn off debugging for this test session and invoke the first CONTINUE restart
 --more--

Backtrace:
 0: (fiasco::record-failure fiasco::failed-assertion :form (is (eql 1 0)) :format-control "Binary predicate ~A failed.~%~ ..)
 1: ((labels naive/test :in naive/test))
 2: ((labels fiasco::run-test-body :in fiasco::run-test-body-in-handlers))
 3: (fiasco::call-with-test-handlers #<closure (lambda nil :in fiasco::run-test-body-in-handlers) {100256D2DB}>)
 4: (fiasco::pretty-run-test #<test naive/test> #<function (labels naive/test :in naive/test) {52DC857B}>)
 5: ((labels #:body-sym547 :in naive/test))
 6: (naive/test)
 7: ((labels fiasco-suites::resource-graph-test :in fiasco-suites::resource-graph-test))
 8: ((labels fiasco::run-test-body :in fiasco::run-test-body-in-handlers))
 9: (fiasco::call-with-test-handlers #<closure (lambda nil :in fiasco::run-test-body-in-handlers) {10025640CB}>)
10: (fiasco::pretty-run-test #<test fiasco-suites::resource-graph-test :tests 1> #<function (labels fiasco-suites::resource-graph-test :in fiasco-suites::resource-graph-test) {52DC501B}>)
11: ((labels #:body-sym546 :in fiasco-suites::resource-graph-test))
12: (fiasco-suites::resource-graph-test)
13: (run-suite-tests #<test fiasco-suites::resource-graph-test :tests 1> :verbose t :stream #<sb-sys:fd-stream for "socket 127.0.0.1:33651, peer: 127.0.0.1:41516" {1004ABE0F3}> :interactive t)
14: (run-tests #<package "RESOURCE-GRAPH-TEST"> :describe-failures t :verbose t :stream #<sb-sys:fd-stream for "socket 127.0.0.1:33651, peer: 127.0.0.1:41516" {1004ABE0F3}> :interactive t)
15: (sb-int:simple-eval-in-lexenv (run-package-tests :verbose t :describe-failures t :interactive ...) #<NULL-LEXENV>)
16: (eval (run-package-tests :verbose t :describe-failures t :interactive ...))
17: ((lambda nil :in slynk:interactive-eval))
```

If you need more I can create a standalone project, let me know!

**Comment by joaotavora** [comment] 2019-11-05 12:17
@arichiardi this was indeed a bug (I was testing with ACL so I couldn't notice it).

Should be fixed, thanks!

**Closed** 2019-11-05 12:17 UTC

**Comment by arichiardi** [comment] 2019-11-06 02:44
@joaotavora thank you! Sorry for the very newbie question, but how do I get an updated version of this library (just starting Common Lisp here :smile:)

**Comment by arichiardi** [comment] 2019-11-06 02:53
Ok clone and figured it out and I can confirm it works thanks!
